// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iitfhgukjxstekxoxppl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpdGZoZ3VranhzdGVreG94cHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NzQzMDIsImV4cCI6MjA2OTI1MDMwMn0.fElaFA7Caxt9ZSpc8hAEQAvStWON4YBBJGZ349Nr35o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});